c1 ------------------------------
417 
332
242
187
123
83

c2 ------------------------------- getdatab mcdockb2
876
711
683
664
627
472
419
360
323
302
252
181
156
112
79

c3 ------------------------------- getdatab2 mcdockb3
1545
1464
1358
1292
1206
1172
1118
1088
961
895
853
735
686

STDERR: Traceback (most recent call last):
  File "/projects/noso3320/software/anaconda/envs/dock_env/bin/unidocktools", line 8, in <module>
    sys.exit(main_cli())
             ^^^^^^^^^^
  File "/projects/noso3320/software/anaconda/envs/dock_env/lib/python3.12/site-packages/unidock_tools/main.py", line 32, in main_cli
    name_module_dict[args["cmd"]].main(args)
  File "/projects/noso3320/software/anaconda/envs/dock_env/lib/python3.12/site-packages/unidock_tools/application/mcdock.py", line 261, in main
    mcd = MultiConfDock(
          ^^^^^^^^^^^^^^
  File "/projects/noso3320/software/anaconda/envs/dock_env/lib/python3.12/site-packages/unidock_tools/application/mcdock.py", line 103, in __init__
    self.generate_conformation(max_nconf=max_nconf, min_rmsd=min_rmsd)
  File "/projects/noso3320/software/anaconda/envs/dock_env/lib/python3.12/site-packages/unidock_tools/utils/logger.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/projects...
2025-08-30 13:55:59,717 - STDOUT: [INFO][2025-08-30 13:55:36,320][main.py 28] [Params] {'cmd': 'mcdock', 'receptor': '/scratch/alpine/noso3320/trem2/unidock/scripts/../data/receptor/cluster1_fixed.pdb', 'ligands': None, 'ligand_index': '/scratch/alpine/noso3320/trem2/unidock/scripts/../results/c3_outputs/chunk_5_attempt_3_ligand_list.txt', 'gen_conf': True, 'max_num_confs_per_ligand': 20, 'min_rmsd': 0.3, 'center_x': 42.328, 'center_y': 28.604, 'center_z': 21.648, 'size_x': 22.5, 'size_y': 22.5, 'size_z': 22.5, 'savedir': '/scra...
2025-08-30 13:55:59,717 - Identified failed ligand: ZINC000835080321.sdfG


c4i ------------------------------- getdata mcdock
1824
1604
1544
1504


  File "/projects/noso3320/software/anaconda/envs/dock_env/lib/python3.12/site-packages/unidock_tools/main.py", line 32, in main_cli
    name_module_dict[args["cmd"]].main(args)
  File "/projects/noso3320/software/anaconda/envs/dock_env/lib/python3.12/site-packages/unidock_tools/application/mcdock.py", line 261, in main
    mcd = MultiConfDock(
          ^^^^^^^^^^^^^^
  File "/projects/noso3320/software/anaconda/envs/dock_env/lib/python3.12/site-packages/unidock_tools/application/mcdock.py", line 103, in __init__
    self.generate_conformation(max_nconf=max_nconf, min_rmsd=min_rmsd)
  File "/projects/noso3320/software/anaconda/envs/dock_env/lib/python3.12/site-packages/unidock_tools/utils/logger.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/projects/noso3320/software/anaconda/envs/dock_env/lib/python3.12/site-packages/unidock_tools/application/mcdock.py", line 225, in generate_conformation
    gen_mol_confs = generate_conf(mol.get_first_mol(), name=prefix,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/noso3320/software/anaconda/envs/dock_env/lib/python3.12/site-packages/unidock_tools/modules/confgen/confgen.py", line 25, in generate_conf
    return cls().generate_conformation(mol, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/noso3320/software/anaconda/envs/dock_env/lib/python3.12/site-packages/unidock_tools/modules/confgen/obabel.py", line 60, in generate_conformation
    mol_list = [mol for mol in Chem.SDMolSupplier(f"{workdir}/{name}.sdf",
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: File error: Bad input file obabel_20250830082426/ZINC001026742242.sdf

c4ii ----------------------------------



c5i ---------------------------------- getdata2
1290
1137
970
875
858

c6 --------------------------------- getdata3
1237
1156
1120
1085

















Hello,

I was wondering if I could receive some clarity with what MCDock does with OpenBabel in the backend. Many of my docking runs terminate with 

```
[stderr] Traceback (most recent call last):
  File "{pathtoenv}/dock_env/bin/unidocktools", line 8, in <module>
    sys.exit(main_cli())
             ^^^^^^^^^^
  File "{pathtoenv}/dock_env/lib/python3.12/site-packages/unidock_tools/main.py", line 32, in main_cli
    name_module_dict[args["cmd"]].main(args)
  File "{pathtoenv}/envs/dock_env/lib/python3.12/site-packages/unidock_tools/application/mcdock.py", line 261, in main
    mcd = MultiConfDock(
          ^^^^^^^^^^^^^^
  File "{pathtoenv}/dock_env/lib/python3.12/site-packages/unidock_tools/application/mcdock.py", line 103, in __init__
    self.generate_conformation(max_nconf=max_nconf, min_rmsd=min_rmsd)
  File "{pathtoenv}/dock_env/lib/python3.12/site-packages/unidock_tools/utils/logger.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
File "{pathtoenv}/dock_env/lib/python3.12/site-packages/unidock_tools/application/mcdock.py", line 225, in generate_conformation
    gen_mol_confs = generate_conf(mol.get_first_mol(), name=prefix,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{pathtoenv}/dock_env/lib/python3.12/site-packages/unidock_tools/modules/confgen/confgen.py", line 25, in generate_conf
    return cls().generate_conformation(mol, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "{pathtoenv}/dock_env/lib/python3.12/site-packages/unidock_tools/modules/confgen/obabel.py", line 60, in generate_conformation
    mol_list = [mol for mol in Chem.SDMolSupplier(f"{workdir}/{name}.sdf",
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: File error: Bad input file obabel_20250830082426/ZINC001026742242.sdf
```

I can see that some `obabel_*` folders are generated in the parent folder of where my script is ran. Each of these folders contains one smi file and one sdf file; the sdf file is empty. I believe this is the issue, but don't know what could be causing this. The existence of the smi file indicates that MCDock might generate a smi mol from the sdf files I give it, but I am uncertain.

Pre-docking, I have even confirmed the validity of each sdf file using obabel, but the results remain the same.

I am using the ZINC database, and was wondering if this was a known issue with sdf files from their database. Any guidance would be appreciated.
